name: Sync to Huggingface hub

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Add remote
        env:
          HF: ${{secrets.HF}}
        run: git clone https://huggingface.co/spaces/rahmanole/demo
      - name: Push to hub
        env: 
          HF: ${{secrets.HF}}
        run: git push --force https://huggingface.co/spaces/rahmanole/demo main
         
