name: Sync to Huggingface hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env: 
          HF_TOKEN: ${{secrets.HF}}
        run: git push --force https://rahmanole:$HF_TOKEN@huggingface.co/spaces/rahmanole/demo main